server:
  port: 8080
  tomcat:
    max-threads: 2000
jdbc:
    enable: true
    type: oracle
druid:
  pool:
    enable: true
spring:
    cache:
        type: redis
    redis:
        cluster:
            nodes:
            - 10.124.143.40:8000
            - 10.124.143.40:8001
            - 10.124.143.40:8002
            - 10.124.143.41:8003
            - 10.124.143.41:8004
            - 10.124.143.41:8005
            - 10.124.143.42:8006
            - 10.124.143.42:8007
        pool:
            max-active: 100
            max-wait: -1
            max-idle: 100
            min-idle: 50
        timeout: 2000

redis:
    cache:
        defaultExpiration: 300
        expires:
          - cacheKey: CBSS_QAM_COMMPARA
            cacheExpire: 180
logs:
  svcperform:
    enable: true
    printResult: true
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 500
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000

qam:
  httpclient:
    rests:
      - domain: accounting
        ip: 10.124.142.87
  datasource:
    jdbcs:
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act1
        password: UOP_ACT1
        provinces: 11,34,86,38,95,ZZZZ
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact1
        username: UOP_ACT1
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act2
        password: UOP_ACT2
        provinces: 97,13,36,31,87
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact2
        username: UOP_ACT2
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act3
        password: UOP_ACT3
        provinces: 59,51,79,81
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact3
        username: UOP_ACT3
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act4
        password: UOP_ACT4
        provinces: 91,75,89,74
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact4
        username: UOP_ACT4
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act5
        password: UOP_ACT5
        provinces: 76,10,88,85
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact5
        username: UOP_ACT5
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act6
        password: UOP_ACT6
        provinces: 17,70
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact6
        username: UOP_ACT6
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act7
        password: UOP_ACT7
        provinces: 18,71,83
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact7
        username: UOP_ACT7
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000
      - driverClassName: oracle.jdbc.driver.OracleDriver
        name: ds_act_uop_act8
        password: UOP_ACT8
        provinces: 19,30,50,84,90
        url: jdbc:oracle:thin:@10.124.0.42:1521:tact8
        username: UOP_ACT8
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxPoolPreparedStatementPerConnectionSize: 200
        maxWait: 4000

