spring:
  profiles:
    active: dev
  application:
    name: @project.name@
  mvc:
    favicon:
      enabled: false

logging:
  config: classpath:logback-act.xml
  
info:
  app:
    title: @project.name@
    description: @project.description@
    version: @project.version@

rest:
  invoke:
    enable: true
